version: '3.3'

services:
  superset:
    image: apache/superset
    ports:
      - '${SUPERSET_PORT}:8088'
    environment:
      SUPERSET_USERNAME: ${SUPERSET_USERNAME}
      SUPERSET_EMAIL: ${SUPERSET_USERNAME_EMAIL}
      SUPERSET_PASSWORD: ${SUPERSET_PASSWORD}
    networks:
      - pg-net

  postgres:
    image: library/postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - '${PG_PORT}:5432'
    restart: always
    networks:
      - pg-net

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '${PG_ADMIN_PORT}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - pg-net

volumes:
  postgres-data:
  pgadmin-data:

networks:
  pg-net: